name: Building

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  building:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: installing dependencies
        run: |
          sudo apt install -y protobuf-compiler

      - name: Building the Project
        run: cargo build --release
